//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuiJi.DataAccess.DF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
